---
language: python
python: "3.8"
sudo: required
services:
  - docker

install:
  - pip install -r molecule/requirements.txt

script:
  - yamllint .
  - ansible-lint molecule/*/converge.yml
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
