---
- name: Converge
  hosts: clients
  roles:
    - role: ../../..
  vars:
    certbot_ca_server: https://certbot-server:14000/dir
    certbot_version: v0.25.1
    certbot_no_verify_ssl: true
    certbot_agree_tos: true
    certbot_account_email: test@example.com
    certbot_certs:
      - name: mycert
        domains:
          - example.com
          - www.example.com
        method: standalone
      - name: wildcard
        domains:
          - '*.example.com'
        method: dns-rfc2136
        params: |-
          --dns-rfc2136-credentials /etc/rfc2136.ini
          --dns-rfc2136-propagation-seconds 5
