---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: certbot-centos7
    image: centos:7
    groups: ['clients']
    networks: [{name: 'molecule-certbot'}]
  - name: certbot-xenial
    image: ubuntu:xenial
    groups: ['clients']
    networks: [{name: 'molecule-certbot'}]
  - name: certbot-bionic
    image: ubuntu:bionic
    groups: ['clients']
    networks: [{name: 'molecule-certbot'}]
  - name: certbot-stretch
    image: debian:stretch
    groups: ['clients']
    networks: [{name: 'molecule-certbot'}]
  - name: certbot-buster
    image: debian:buster
    groups: ['clients']
    networks: [{name: 'molecule-certbot'}]
  - name: certbot-server
    image: golang:stretch
    groups: ['servers']
    networks: [{name: 'molecule-certbot'}]
  - name: certbot-dns
    image: ubuntu:xenial
    groups: ['nameservers']
    networks: [{name: 'molecule-certbot'}]
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
scenario:
  name: default
verifier:
  name: testinfra
